# Validates markdown links to check for bad / invalid / broken links.
# Uses mlc_config.json in root to configure patterns to ignore etc.
#
# https://github.com/marketplace/actions/markdown-link-check
#
name: Check Markdown links

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'